### PR TITLE
CSS changes labels, displayStats, map

### PR DESCRIPTION
**Pull request by saynegrojas**
Changes to CSS

### CODE REVIEW

**Comment by dhuan008** [comment]
- I'm partial to blue, so I won't say anything more about the red. 
- You removed the hover opacity? Its included by default in materialize's hover classes and I think in google's material design so i think we should keep that. It is a barely noticeable effect so it might not matter.
Hover_opacity
- Not sure what the display status hover when long lat labels clicked is.

**Comment by dhuan008** [comment]
`/*set displays to match the label color*/
.displayStats {
  color: #9E9E9E;
}
.displayStats:hover {
  color: #26a69a;
  opacity: .74;
}
label:hover {
  opacity: 0.7;
}`

- What does this css code do? 
- What does the "displays" in your comment refer to? Going by the code it looks like the table headers? Do you mean the table? And are you trying to modify table data instead? 
- I don't think you're using hover correctly the code has no effect. [https://www.w3schools.com/css/css_pseudo_classes.asp](url)

**Comment by saynegrojas** [comment]
I meant the "displayStats" color. And when I click inside the input-fields, the color of the label turns kind of a teal color. Initially, the labels for the lat and long are grey. I tried to match it with the displayStats colors. 
I'm going to change color back to the blue color.

**Comment by dhuan008** [comment]
The color changes to teal? it should be grey and black, I'll check that later. If we what to user input to change to red text we can do that.
Do you mean changing the button back to blue? We can keep it as red, I mean the opacity isn't there anymore. The gif isn't that clear but the blue becomes kind of see through while the red is still solid. color:RGBA() you removed the A part when you changed it to red. the last number controls the opacity.

**Pull request closed without merging**
