### PR TITLE
MVP for mini presentation tomorrow?

### PR DESCRIPTION
**Pull request by dhuan008**
- Added ArcGIS call using ajax.
  - Our second api and the ajax call to it.

- Implemented reverse geocoding of user coordinates
  - Using the ArcGIS api to lookup city

- Rearranged and partially organized code in to functions/sections
  - Self-explanatory?

### CODE REVIEW

**Comment by dhuan008** [comment]
- I forgot to put the hide classes back in for the maps and tables. We can do that easily.

- I forgot to add the error checking back in. We can do that tomorrow unless someone want to do it before.

**Comment by Andymendez100** [comment]
You bug check everything with the second api? Everything still working as planned?

**Comment by dhuan008** [comment]
Yeah I tested it, working. I'll add the error checking in now almost done.

**Comment by Andymendez100** [comment]
What is line 137 doing?

**Pull request merged**
